{
  'type': 'object',
  'properties':
    {
      'app': { '$ref': 'config/schemas/app.yaml' },
      'database': { '$ref': 'config/schemas/database.yaml' },
      'jwt': { '$ref': 'config/schemas/jwt.yaml' },
      'redis': { '$ref': 'config/schemas/redis.yaml' },
      'short_code': { '$ref': 'config/schemas/short_code.yaml' },
      'cache': { '$ref': 'config/schemas/cache.yaml' },
      'certificates': { '$ref': 'config/schemas/certificates.yaml' },
      'rate_limiter': { '$ref': 'config/schemas/rate_limiter.yaml' },
    },
  'required': ['app', 'database', 'jwt', 'redis', 'short_code', 'cache', 'certificates', 'rate_limiter'],
}
